# BANNER
# http://patorjk.com/software/taag/#p=display&h=0&v=0&f=Standard&t=Nebula-Dev
spring:
  banner:
    location: classpath:banner-dev.txt

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      # Path at which the console is available.http://localhost:8080/h2-console
      path: /h2-console